---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./flagger.yaml
  - ./gitea.yaml
  - ./gitlab.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./harbor.yaml
  - ./hashicorp.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./loft-sh.yaml
  - ./metrics-server.yaml
  - ./minio.yaml
  - ./oauth2-proxy.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./traefik.yaml
  - ./weave-gitops.yaml
